#!/bin/bash

[[ "$EUID" -eq "0" ]] || { sudo -p "Please enter your password to continue: " "$0" "$@"; exit $?; }

set -e

rm -f ubuntu.iso

source fetch_build.conf

[ -z "$DOWNLOAD_ISO" ] && wget -O ubuntu.iso "https://releases.ubuntu.com/23.10.1/ubuntu-23.10.1-desktop-amd64.iso" || wget -O ubuntu.iso "$DOWNLOAD_ISO"

make
